# Form implementation generated from reading ui file '.\design\adminpanel.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-color: rgb(32,37,43);")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.label.setStyleSheet("background-color: rgba(14,15,20, 0.75);\n"
"border: 1px solid gray;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(-10, 10, 411, 31))
        self.label_2.setStyleSheet("background-color: none;\n"
"color: white;\n"
"margin: 0 auto;\n"
"font-size: 20px;")
        self.label_2.setObjectName("label_2")
        self.pushButton_add = QtWidgets.QPushButton(parent=Form)
        self.pushButton_add.setGeometry(QtCore.QRect(60, 240, 75, 24))
        self.pushButton_add.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_change = QtWidgets.QPushButton(parent=Form)
        self.pushButton_change.setGeometry(QtCore.QRect(160, 240, 75, 24))
        self.pushButton_change.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.pushButton_change.setObjectName("pushButton_change")
        self.pushButton_delete = QtWidgets.QPushButton(parent=Form)
        self.pushButton_delete.setGeometry(QtCore.QRect(260, 240, 75, 24))
        self.pushButton_delete.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 261, 21))
        self.label_3.setStyleSheet("background-color: none;\n"
"color: white;\n"
"margin: 0 auto;\n"
"font-size: 14px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 261, 21))
        self.label_4.setStyleSheet("background-color: none;\n"
"color: white;\n"
"margin: 0 auto;\n"
"font-size: 14px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(-20, 110, 271, 21))
        self.label_5.setStyleSheet("background-color: none;\n"
"color: white;\n"
"margin: 0 auto;\n"
"font-size: 14px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(-20, 140, 271, 21))
        self.label_6.setStyleSheet("background-color: none;\n"
"color: white;\n"
"margin: 0 auto;\n"
"font-size: 14px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(-20, 170, 271, 21))
        self.label_7.setStyleSheet("background-color: none;\n"
"color: white;\n"
"margin: 0 auto;\n"
"font-size: 14px;")
        self.label_7.setObjectName("label_7")
        self.lineedit_learntype = QtWidgets.QLineEdit(parent=Form)
        self.lineedit_learntype.setGeometry(QtCore.QRect(220, 50, 151, 21))
        self.lineedit_learntype.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.lineedit_learntype.setObjectName("lineedit_learntype")
        self.lineedit_learntime = QtWidgets.QLineEdit(parent=Form)
        self.lineedit_learntime.setGeometry(QtCore.QRect(220, 80, 151, 21))
        self.lineedit_learntime.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.lineedit_learntime.setObjectName("lineedit_learntime")
        self.lineedit_learnprice_month = QtWidgets.QLineEdit(parent=Form)
        self.lineedit_learnprice_month.setGeometry(QtCore.QRect(220, 110, 151, 21))
        self.lineedit_learnprice_month.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.lineedit_learnprice_month.setObjectName("lineedit_learnprice_month")
        self.lineedit_learntime_sem = QtWidgets.QLineEdit(parent=Form)
        self.lineedit_learntime_sem.setGeometry(QtCore.QRect(220, 140, 151, 21))
        self.lineedit_learntime_sem.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.lineedit_learntime_sem.setObjectName("lineedit_learntime_sem")
        self.lineedit_learnprice_year = QtWidgets.QLineEdit(parent=Form)
        self.lineedit_learnprice_year.setGeometry(QtCore.QRect(220, 170, 151, 21))
        self.lineedit_learnprice_year.setStyleSheet("background-color: rgba(43,48,55, 0.8);\n"
"border: 1px solid gray;\n"
"border-radius: 5px;\n"
"color: white;")
        self.lineedit_learnprice_year.setObjectName("lineedit_learnprice_year")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Добавить, изменить, удалить форму"))
        self.pushButton_add.setText(_translate("Form", "Добавить"))
        self.pushButton_change.setText(_translate("Form", "Изменить"))
        self.pushButton_delete.setText(_translate("Form", "Удалить"))
        self.label_3.setText(_translate("Form", "Форма обучения:"))
        self.label_4.setText(_translate("Form", "Срок обучения (мес):"))
        self.label_5.setText(_translate("Form", "Стоимость обучения(за мес.):"))
        self.label_6.setText(_translate("Form", "Стоимость обучения(за сем.):"))
        self.label_7.setText(_translate("Form", "Стоимость обучения (за год):"))
